[platformio]
boards_dir   = boards
default_envs = knomi

[env]
framework     = arduino
monitor_speed = 115200
build_flags   =
    -Wall
    -Isrc
    -DLV_CONF_PATH="lv_conf.h"

lib_deps =
    SPI
    TFT_eSPI=https://github.com/Bodmer/TFT_eSPI
    lvgl/lvgl@~9.0.0

[env:knomi]
platform               = espressif32
board                  = knomi
board_build.partitions = knomi_partitions.csv
build_flags            =
    ${env.build_flags}
    -DKNOMI
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_filters = esp32_exception_decoder

[env:knomi_t0]
extends     = env:knomi
build_flags = 
    ${env:knomi.build_flags}
    -DDEV_ID=\"T0\"

[env:knomi_t1]
extends     = env:knomi
build_flags = 
    ${env:knomi.build_flags}
    -DDEV_ID=\"T1\"

[env:knomi_t2]
extends = env:knomi
build_flags = 
    ${env:knomi.build_flags}
    -DDEV_ID=\"T2\"

[env:knomi_t3]
extends = env:knomi
build_flags = 
    ${env:knomi.build_flags}
    -DDEV_ID=\"T3\"

[env:knomi_t4]
extends = env:knomi
build_flags = 
    ${env:knomi.build_flags}
    -DDEV_ID=\"T4\"

[env:knomi_t5]
extends = env:knomi
build_flags = 
    ${env:knomi.build_flags}
    -DDEV_ID=\"T5\"

[env:knomi_t6]
extends = env:knomi
build_flags = 
    ${env:knomi.build_flags}
    -DDEV_ID=\"T6\"